---
- name: Install Apache
  yum: name={{ item }} state=latest
  with_items:
   - httpd
   - php
   - php-mysql
   - php-mbstring
   - mod_ssl
   - php-mhash
   - php-gd

- name: Start httpd service
  service:
    name: httpd
    state: started
    enabled: yes
