- name: Configuring repositories
  shell: |

      yum install -y yum-utils &&
      yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
      yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm &&
      yum-config-manager --enable remi-php56


- name: Install PHP 5.6
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-bcmath
    - php-cli
    - php-common
    - php-dba
    - php-devel
    - php-gd
    - php-ldap
    - php-mbstring
    - php-mysql
    - php-odbc
    - php-pdo 
    - php-pear
    - php-pgsql
    - php-soap
    - php-xml
    - php-xmlrpc

