- name: Configuring repositories
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Enable PHP 7.0 repository
  shell: |
      yum-config-manager --enable remi-php70


- name: Install PHP 7.0
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-bcmath
    - php-cli
    - php-common
    - php-dba
    - php-devel
    - php-gd
    - php-ldap
    - php-mbstring
    - php-mysql
    - php-odbc
    - php-pdo 
    - php-pear
    - php-pgsql
    - php-soap
    - php-xml
    - php-xmlrpc

